package omarchy

import (
	"crypto/sha256"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"aether/internal/platform"
)

const managedMarker = ".aether-managed"

// Capabilities describes the installed Omarchy integration.
type Capabilities struct {
	Available    bool     `json:"available"`
	Version      string   `json:"version"`
	ThemesDir    string   `json:"themesDir"`
	StateDir     string   `json:"stateDir"`
	CurrentTheme string   `json:"currentTheme"`
	OverrideApps []string `json:"overrideApps"`
}

var themeOverrideApps = []string{
	"alacritty", "btop", "chromium", "foot", "ghostty", "icons", "kitty", "neovim", "vscode",
}

var themeOverrideAppSet = map[string]bool{
	"alacritty": true,
	"btop":      true,
	"chromium":  true,
	"foot":      true,
	"ghostty":   true,
	"icons":     true,
	"kitty":     true,
	"neovim":    true,
	"vscode":    true,
}

// ThemeOverrideApps returns applications whose per-theme files Omarchy reads.
func ThemeOverrideApps() []string {
	return append([]string(nil), themeOverrideApps...)
}

// SupportsThemeOverride reports whether Omarchy consumes an app override file.
func SupportsThemeOverride(app string) bool {
	return themeOverrideAppSet[app]
}

// IsInstalled reports whether the public Omarchy command is available.
func IsInstalled() bool {
	return runtime.GOOS == "linux" && platform.CommandExists("omarchy")
}

// DetectCapabilities returns the native paths and active theme for Omarchy.
func DetectCapabilities() Capabilities {
	capabilities := Capabilities{
		Available:    IsInstalled(),
		ThemesDir:    UserThemesDir(),
		StateDir:     CurrentStateDir(),
		CurrentTheme: GetCurrentThemeName(),
		OverrideApps: ThemeOverrideApps(),
	}
	if !capabilities.Available {
		return capabilities
	}
	if output, err := platform.RunSync("omarchy", "version"); err == nil {
		capabilities.Version = strings.TrimSpace(output)
	}
	return capabilities
}

// UserThemesDir returns Omarchy's native user theme root.
func UserThemesDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "omarchy", "themes")
}

// CurrentStateDir returns Omarchy's authoritative runtime theme directory.
func CurrentStateDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "state", "omarchy", "current")
}

// CurrentThemeColorsPath returns the active native theme's colors.toml.
func CurrentThemeColorsPath() string {
	return filepath.Join(CurrentStateDir(), "theme", "colors.toml")
}

// IsManagedThemeDir reports whether a theme directory belongs to Aether.
// The colors.toml check recognizes themes generated before ownership markers.
func IsManagedThemeDir(path string) bool {
	if _, err := os.Stat(filepath.Join(path, managedMarker)); err == nil {
		return true
	}
	data, err := os.ReadFile(filepath.Join(path, "colors.toml"))
	return err == nil && strings.Contains(string(data), "Generated by Aether")
}

// MarkManagedTheme records that Aether may safely replace the theme directory.
func MarkManagedTheme(path string) error {
	return os.WriteFile(filepath.Join(path, managedMarker), []byte("aether\n"), 0o644)
}

// ThemeExists reports whether name would collide with a user or stock theme.
func ThemeExists(name string) bool {
	for _, root := range []string{UserThemesDir(), stockThemesDir()} {
		if info, err := os.Stat(filepath.Join(root, name)); err == nil && info.IsDir() {
			return true
		}
	}
	return false
}

// ActivateTheme applies a source theme through Omarchy's public CLI. When a
// wallpaper is supplied, Omarchy preserves the current background until the
// requested image can be selected explicitly.
func ActivateTheme(name, wallpaper string) error {
	return ActivateThemeWithInstall(name, wallpaper, func(activate func() error) error {
		return activate()
	})
}

// ActivateThemeWithInstall snapshots the current background before installing a
// generated bundle. install must call activate once after installation and roll
// back the bundle before returning an activation error, so the old background's
// original path can be reused when its contents match. Recovery snapshots remain
// in Aether's data directory when selected. This does not serialize transactions.
func ActivateThemeWithInstall(name, wallpaper string, install func(activate func() error) error) error {
	if !IsInstalled() {
		return fmt.Errorf("omarchy is not installed")
	}
	if err := validateThemeName(name); err != nil {
		return err
	}
	previousBackground := currentBackgroundPath()
	snapshot := ""
	var previousDigest [sha256.Size]byte
	previousInRuntime := true
	keepSnapshot := false
	if previousBackground != "" {
		info, err := os.Stat(previousBackground)
		if err != nil {
			return fmt.Errorf("inspect previous background: %w", err)
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("previous background is not a regular file: %s", previousBackground)
		}
		// Omarchy replaces copied runtime themes, so even an existing path can
		// name different bytes after failure. Keep recovery media outside it.
		recoveryRoot := filepath.Join(platform.DataDir(), "background-recovery")
		if err := os.MkdirAll(recoveryRoot, 0o700); err != nil {
			return fmt.Errorf("create background recovery directory: %w", err)
		}
		recoveryDir, err := os.MkdirTemp(recoveryRoot, "background-")
		if err != nil {
			return fmt.Errorf("reserve previous background snapshot: %w", err)
		}
		defer func() {
			if !keepSnapshot {
				if err := os.RemoveAll(recoveryDir); err != nil {
					log.Printf("Warning: could not remove background snapshot %s: %v", recoveryDir, err)
				}
			}
		}()
		snapshot = filepath.Join(recoveryDir, filepath.Base(previousBackground))
		if err := platform.CopyFile(previousBackground, snapshot); err != nil {
			return fmt.Errorf("snapshot previous background %q: %w", previousBackground, err)
		}
		previousDigest, err = backgroundDigest(snapshot)
		if err != nil {
			return fmt.Errorf("verify previous background snapshot: %w", err)
		}
		if runtimeDir, err := filepath.EvalSymlinks(CurrentStateDir()); err == nil {
			if relative, err := filepath.Rel(runtimeDir, previousBackground); err == nil {
				previousInRuntime = filepath.IsLocal(relative)
			}
		}
	}
	activationStarted := false
	err := install(func() error {
		if err := rememberPreviousTheme(name); err != nil {
			return err
		}
		activationStarted = true
		if wallpaper == "" {
			if _, err := platform.RunSync("omarchy", "theme", "set", name); err != nil {
				return fmt.Errorf("activate Omarchy theme %q: %w", name, err)
			}
			return nil
		}

		if _, err := platform.RunSync("omarchy", "theme", "bg", "set", wallpaper); err != nil {
			return fmt.Errorf("set Omarchy background: %w", err)
		}
		if _, err := platform.RunSyncEnv(
			map[string]string{"OMARCHY_THEME_SKIP_BACKGROUND": "1"},
			"omarchy", "theme", "set", name,
		); err != nil {
			return fmt.Errorf("activate Omarchy theme %q: %w", name, err)
		}
		return nil
	})
	if err != nil && activationStarted && previousBackground != "" {
		restorePath := snapshot
		if !previousInRuntime {
			if digest, readErr := backgroundDigest(previousBackground); readErr == nil && digest == previousDigest {
				restorePath = previousBackground
			}
		}
		keepSnapshot = restorePath == snapshot
		if _, restoreErr := platform.RunSync("omarchy", "theme", "bg", "set", restorePath); restoreErr != nil {
			keepSnapshot = true
			return fmt.Errorf("%w; restore previous background: %v; recovery copy: %s", err, restoreErr, snapshot)
		}
	}
	return err
}

func backgroundDigest(path string) ([sha256.Size]byte, error) {
	var digest [sha256.Size]byte
	info, err := os.Stat(path)
	if err != nil {
		return digest, err
	}
	if !info.Mode().IsRegular() {
		return digest, fmt.Errorf("background is not a regular file: %s", path)
	}
	file, err := os.Open(path)
	if err != nil {
		return digest, err
	}
	defer file.Close()
	hash := sha256.New()
	if _, err := io.Copy(hash, file); err != nil {
		return digest, err
	}
	copy(digest[:], hash.Sum(nil))
	return digest, nil
}

func currentBackgroundPath() string {
	path, err := filepath.EvalSymlinks(filepath.Join(CurrentStateDir(), "background"))
	if err != nil {
		return ""
	}
	return path
}

// RevertTheme activates the last non-Aether Omarchy theme.
func RevertTheme() error {
	current := GetCurrentThemeName()
	if current == "" || !IsManagedThemeDir(filepath.Join(UserThemesDir(), current)) {
		return nil
	}

	data, err := os.ReadFile(previousThemeFile())
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("read previous Omarchy theme: %w", err)
		}
		data = []byte("tokyo-night")
	}
	name := strings.TrimSpace(string(data))
	if err := validateThemeName(name); err != nil {
		return fmt.Errorf("invalid previous Omarchy theme: %w", err)
	}
	_, err = platform.RunSync("omarchy", "theme", "set", name)
	if err != nil {
		return fmt.Errorf("restore Omarchy theme %q: %w", name, err)
	}
	return nil
}

func rememberPreviousTheme(next string) error {
	if !IsManagedThemeDir(filepath.Join(UserThemesDir(), next)) {
		return nil
	}
	current := GetCurrentThemeName()
	if current == "" || current == next || IsManagedThemeDir(filepath.Join(UserThemesDir(), current)) {
		return nil
	}
	if err := platform.EnsureDir(filepath.Dir(previousThemeFile())); err != nil {
		return fmt.Errorf("create Aether config directory: %w", err)
	}
	if err := os.WriteFile(previousThemeFile(), []byte(current+"\n"), 0o644); err != nil {
		return fmt.Errorf("remember current Omarchy theme: %w", err)
	}
	return nil
}

func previousThemeFile() string {
	return filepath.Join(platform.ConfigDir(), "previous-omarchy-theme")
}

func validateThemeName(name string) error {
	if name == "" || name == "." || name == ".." || strings.HasPrefix(name, ".") || filepath.Base(name) != name {
		return fmt.Errorf("invalid Omarchy theme name %q", name)
	}
	return nil
}
