// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustPaletteColors(arg1, arg2) {
    return window['go']['main']['App']['AdjustPaletteColors'](arg1, arg2);
}

export function ApplyBlueprint(arg1) {
    return window['go']['main']['App']['ApplyBlueprint'](arg1);
}

export function ApplyOmarchyThemeByName(arg1) {
    return window['go']['main']['App']['ApplyOmarchyThemeByName'](arg1);
}

export function ApplyTheme(arg1) {
    return window['go']['main']['App']['ApplyTheme'](arg1);
}

export function ApplyWallpaperOnly(arg1) {
    return window['go']['main']['App']['ApplyWallpaperOnly'](arg1);
}

export function BlueprintExists(arg1) {
    return window['go']['main']['App']['BlueprintExists'](arg1);
}

export function BlurWallpaper(arg1) {
    return window['go']['main']['App']['BlurWallpaper'](arg1);
}

export function CancelBatchProcessing() {
    return window['go']['main']['App']['CancelBatchProcessing']();
}

export function CancelExternalImport(arg1) {
    return window['go']['main']['App']['CancelExternalImport'](arg1);
}

export function CancelFavoritesExport() {
    return window['go']['main']['App']['CancelFavoritesExport']();
}

export function ChooseWallpaperFolder() {
    return window['go']['main']['App']['ChooseWallpaperFolder']();
}

export function ClearTheme() {
    return window['go']['main']['App']['ClearTheme']();
}

export function CloseIPC() {
    return window['go']['main']['App']['CloseIPC']();
}

export function ComputeVariables(arg1, arg2, arg3) {
    return window['go']['main']['App']['ComputeVariables'](arg1, arg2, arg3);
}

export function ConfirmExternalImport(arg1) {
    return window['go']['main']['App']['ConfirmExternalImport'](arg1);
}

export function ContrastRatio(arg1, arg2) {
    return window['go']['main']['App']['ContrastRatio'](arg1, arg2);
}

export function DeleteBlueprint(arg1) {
    return window['go']['main']['App']['DeleteBlueprint'](arg1);
}

export function DownloadWallpaper(arg1) {
    return window['go']['main']['App']['DownloadWallpaper'](arg1);
}

export function ExportFavorites(arg1) {
    return window['go']['main']['App']['ExportFavorites'](arg1);
}

export function ExportTheme(arg1) {
    return window['go']['main']['App']['ExportTheme'](arg1);
}

export function ExtractColors(arg1, arg2, arg3) {
    return window['go']['main']['App']['ExtractColors'](arg1, arg2, arg3);
}

export function ExtractColorsFromImages(arg1, arg2, arg3) {
    return window['go']['main']['App']['ExtractColorsFromImages'](
        arg1,
        arg2,
        arg3
    );
}

export function GenerateGradient(arg1, arg2) {
    return window['go']['main']['App']['GenerateGradient'](arg1, arg2);
}

export function GeneratePaletteFromColor(arg1) {
    return window['go']['main']['App']['GeneratePaletteFromColor'](arg1);
}

export function GetFavorites() {
    return window['go']['main']['App']['GetFavorites']();
}

export function GetFocusTab() {
    return window['go']['main']['App']['GetFocusTab']();
}

export function GetIconThemePreview(arg1) {
    return window['go']['main']['App']['GetIconThemePreview'](arg1);
}

export function GetInitialState() {
    return window['go']['main']['App']['GetInitialState']();
}

export function GetOmarchyCapabilities() {
    return window['go']['main']['App']['GetOmarchyCapabilities']();
}

export function GetPendingExternalImport() {
    return window['go']['main']['App']['GetPendingExternalImport']();
}

export function GetPreview(arg1) {
    return window['go']['main']['App']['GetPreview'](arg1);
}

export function GetReleaseStatus(arg1) {
    return window['go']['main']['App']['GetReleaseStatus'](arg1);
}

export function GetSettings() {
    return window['go']['main']['App']['GetSettings']();
}

export function GetTemplateColors() {
    return window['go']['main']['App']['GetTemplateColors']();
}

export function GetThemeColors() {
    return window['go']['main']['App']['GetThemeColors']();
}

export function GetThumbnail(arg1) {
    return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetWallhavenConfig() {
    return window['go']['main']['App']['GetWallhavenConfig']();
}

export function GetWallpaperTags() {
    return window['go']['main']['App']['GetWallpaperTags']();
}

export function HandleDroppedFiles(arg1) {
    return window['go']['main']['App']['HandleDroppedFiles'](arg1);
}

export function HandleIPC(arg1) {
    return window['go']['main']['App']['HandleIPC'](arg1);
}

export function ImportFileDialog(arg1) {
    return window['go']['main']['App']['ImportFileDialog'](arg1);
}

export function IsFavorite(arg1) {
    return window['go']['main']['App']['IsFavorite'](arg1);
}

export function IsFavoritesExportRunning() {
    return window['go']['main']['App']['IsFavoritesExportRunning']();
}

export function IsMacOS() {
    return window['go']['main']['App']['IsMacOS']();
}

export function IsOmarchyInstalled() {
    return window['go']['main']['App']['IsOmarchyInstalled']();
}

export function IsPreviewCached(arg1) {
    return window['go']['main']['App']['IsPreviewCached'](arg1);
}

export function ListBlueprints() {
    return window['go']['main']['App']['ListBlueprints']();
}

export function ListInstalledIconThemes() {
    return window['go']['main']['App']['ListInstalledIconThemes']();
}

export function LoadBlueprint(arg1) {
    return window['go']['main']['App']['LoadBlueprint'](arg1);
}

export function LoadOmarchyThemes() {
    return window['go']['main']['App']['LoadOmarchyThemes']();
}

export function OpenExternalImportInEditor(arg1) {
    return window['go']['main']['App']['OpenExternalImportInEditor'](arg1);
}

export function OpenFileDialog() {
    return window['go']['main']['App']['OpenFileDialog']();
}

export function PreviewExtractColors(arg1, arg2, arg3) {
    return window['go']['main']['App']['PreviewExtractColors'](
        arg1,
        arg2,
        arg3
    );
}

export function ReadImageAsDataURL(arg1) {
    return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function RefreshInstalledIconThemes() {
    return window['go']['main']['App']['RefreshInstalledIconThemes']();
}

export function ResetState() {
    return window['go']['main']['App']['ResetState']();
}

export function SaveAndApplyTheme(arg1) {
    return window['go']['main']['App']['SaveAndApplyTheme'](arg1);
}

export function SaveBlueprint(arg1) {
    return window['go']['main']['App']['SaveBlueprint'](arg1);
}

export function SaveDataURLToFile(arg1, arg2) {
    return window['go']['main']['App']['SaveDataURLToFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
    return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWallhavenConfig(arg1) {
    return window['go']['main']['App']['SaveWallhavenConfig'](arg1);
}

export function SaveWallpaperTags(arg1) {
    return window['go']['main']['App']['SaveWallpaperTags'](arg1);
}

export function ScanLocalWallpapers() {
    return window['go']['main']['App']['ScanLocalWallpapers']();
}

export function SearchWallhaven(arg1) {
    return window['go']['main']['App']['SearchWallhaven'](arg1);
}

export function SetExtractionMode(arg1) {
    return window['go']['main']['App']['SetExtractionMode'](arg1);
}

export function SetWallhavenAPIKey(arg1) {
    return window['go']['main']['App']['SetWallhavenAPIKey'](arg1);
}

export function StartBatchProcessing(arg1, arg2) {
    return window['go']['main']['App']['StartBatchProcessing'](arg1, arg2);
}

export function StartUpgrade() {
    return window['go']['main']['App']['StartUpgrade']();
}

export function SyncState(arg1) {
    return window['go']['main']['App']['SyncState'](arg1);
}

export function ThemeFolderExists(arg1) {
    return window['go']['main']['App']['ThemeFolderExists'](arg1);
}

export function ToggleFavorite(arg1, arg2, arg3) {
    return window['go']['main']['App']['ToggleFavorite'](arg1, arg2, arg3);
}
