// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {color} from '../models';
import {theme} from '../models';
import {main} from '../models';
import {favorites} from '../models';
import {icontheme} from '../models';
import {omarchy} from '../models';
import {ipc} from '../models';
import {wallpaper} from '../models';
import {wallhaven} from '../models';

export function AdjustPaletteColors(
    arg1: Array<string>,
    arg2: color.Adjustments
): Promise<Array<string>>;

export function ApplyBlueprint(arg1: string): Promise<theme.ApplyResult>;

export function ApplyOmarchyThemeByName(arg1: string): Promise<void>;

export function ApplyTheme(
    arg1: main.ApplyThemeRequest
): Promise<theme.ApplyResult>;

export function BlueprintExists(arg1: string): Promise<boolean>;

export function CancelBatchProcessing(): Promise<void>;

export function CancelExternalImport(arg1: string): Promise<void>;

export function ChooseWallpaperFolder(): Promise<string>;

export function ClearTheme(): Promise<void>;

export function CloseIPC(): Promise<void>;

export function ComputeVariables(
    arg1: Array<string>,
    arg2: Record<string, string>,
    arg3: boolean
): Promise<Record<string, string>>;

export function ConfirmExternalImport(arg1: string): Promise<void>;

export function ContrastRatio(arg1: string, arg2: string): Promise<number>;

export function DeleteBlueprint(arg1: string): Promise<void>;

export function DownloadWallpaper(arg1: string): Promise<string>;

export function ExportTheme(arg1: main.ExportThemeRequest): Promise<string>;

export function ExtractColors(
    arg1: string,
    arg2: boolean,
    arg3: string
): Promise<any>;

export function ExtractColorsFromImages(
    arg1: Array<string>,
    arg2: boolean,
    arg3: string
): Promise<main.ExtractFromImagesResult>;

export function GenerateGradient(arg1: string, arg2: string): Promise<any>;

export function GeneratePaletteFromColor(arg1: string): Promise<any>;

export function GetFavorites(): Promise<Array<favorites.Favorite>>;

export function GetFocusTab(): Promise<string>;

export function GetIconThemePreview(
    arg1: string
): Promise<icontheme.ThemePreview>;

export function GetInitialState(): Promise<theme.StateSnapshot>;

export function GetOmarchyCapabilities(): Promise<omarchy.Capabilities>;

export function GetPendingExternalImport(): Promise<main.ExternalImportPreview>;

export function GetPreview(arg1: string): Promise<string>;

export function GetReleaseStatus(arg1: string): Promise<Record<string, any>>;

export function GetSettings(): Promise<Record<string, any>>;

export function GetTemplateColors(): Promise<Record<string, Array<string>>>;

export function GetThemeColors(): Promise<Record<string, string>>;

export function GetThumbnail(arg1: string): Promise<string>;

export function GetWallhavenConfig(): Promise<Record<string, any>>;

export function GetWallpaperTags(): Promise<Record<string, any>>;

export function HandleDroppedFiles(arg1: Array<string>): Promise<string>;

export function HandleIPC(arg1: ipc.Request): Promise<ipc.Response>;

export function ImportFileDialog(arg1: string): Promise<main.ImportResult>;

export function IsFavorite(arg1: string): Promise<boolean>;

export function IsMacOS(): Promise<boolean>;

export function IsOmarchyInstalled(): Promise<boolean>;

export function IsPreviewCached(arg1: string): Promise<boolean>;

export function ListBlueprints(): Promise<Array<Record<string, any>>>;

export function ListInstalledIconThemes(): Promise<
    Array<icontheme.ThemeSummary>
>;

export function LoadBlueprint(arg1: string): Promise<void>;

export function LoadOmarchyThemes(): Promise<Array<omarchy.Theme>>;

export function OpenExternalImportInEditor(arg1: string): Promise<void>;

export function OpenFileDialog(): Promise<string>;

export function PreviewExtractColors(
    arg1: string,
    arg2: boolean,
    arg3: string
): Promise<any>;

export function ReadImageAsDataURL(arg1: string): Promise<string>;

export function RefreshInstalledIconThemes(): Promise<
    Array<icontheme.ThemeSummary>
>;

export function ResetState(): Promise<void>;

export function SaveAndApplyTheme(
    arg1: main.SaveAndApplyThemeRequest
): Promise<theme.ApplyResult>;

export function SaveBlueprint(arg1: main.SaveBlueprintRequest): Promise<void>;

export function SaveDataURLToFile(arg1: string, arg2: string): Promise<string>;

export function SaveSettings(arg1: Record<string, any>): Promise<void>;

export function SaveWallhavenConfig(arg1: Record<string, any>): Promise<void>;

export function SaveWallpaperTags(arg1: Record<string, any>): Promise<void>;

export function ScanLocalWallpapers(): Promise<Array<wallpaper.WallpaperInfo>>;

export function SearchWallhaven(
    arg1: wallhaven.SearchParams
): Promise<wallhaven.SearchResult>;

export function SetExtractionMode(arg1: string): Promise<void>;

export function SetWallhavenAPIKey(arg1: string): Promise<void>;

export function StartBatchProcessing(
    arg1: Array<string>,
    arg2: boolean
): Promise<void>;

export function StartUpgrade(): Promise<void>;

export function SyncState(arg1: main.SyncStateRequest): Promise<void>;

export function ToggleFavorite(
    arg1: string,
    arg2: string,
    arg3: Record<string, any>
): Promise<boolean>;
